#!/bin/bash


/usr/local/bin/okta-awscli -u <Oktauser> -p <PWD> -r 1

aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com
